source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

platform :ios, ‘7.0’

target 'wegoal' do
  pod 'AFNetworking', '~> 2.6.1'
  pod 'Toast', '~> 2.4'
  pod 'MJExtension'
  pod 'SDWebImage'
  pod 'SVPullToRefresh'
  pod "MWPhotoBrowser"
  pod 'SDCycleScrollView'  

end
